<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Assecor.Backend.Configuration\Assecor.Backend.Configuration.csproj" />
    <ProjectReference Include="..\Assecor.Backend.Dal.IoC\Assecor.Backend.Dal.IoC.csproj" />
    <ProjectReference Include="..\Assecor.Backend.Mappings\Assecor.Backend.Mappings.csproj" />
    <ProjectReference Include="..\Assecor.Services.Contracts\Assecor.Backend.Services.Contracts.csproj" />
    <ProjectReference Include="..\Assecor.Services.IoC\Assecor.Backend.Services.IoC.csproj" />
  </ItemGroup>

</Project>
